image: openjdk:14-slim-buster

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - ./gradlew test

staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev git
    - gem install dpl
    - dpl --provider=heroku --app=ddd-ecommerce --api-key=$HEROKU_STAGING_API_KEY
  only:
    - master
